/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AboutSection {
    }
    interface ContactSection {
    }
    interface ExperienceSection {
    }
    interface FeaturedProjectsSection {
    }
    interface HeroSection {
    }
    interface PortfolioPage {
    }
    interface SiteHeader {
    }
    interface WhatIDoSection {
    }
}
declare global {
    interface HTMLAboutSectionElement extends Components.AboutSection, HTMLStencilElement {
    }
    var HTMLAboutSectionElement: {
        prototype: HTMLAboutSectionElement;
        new (): HTMLAboutSectionElement;
    };
    interface HTMLContactSectionElement extends Components.ContactSection, HTMLStencilElement {
    }
    var HTMLContactSectionElement: {
        prototype: HTMLContactSectionElement;
        new (): HTMLContactSectionElement;
    };
    interface HTMLExperienceSectionElement extends Components.ExperienceSection, HTMLStencilElement {
    }
    var HTMLExperienceSectionElement: {
        prototype: HTMLExperienceSectionElement;
        new (): HTMLExperienceSectionElement;
    };
    interface HTMLFeaturedProjectsSectionElement extends Components.FeaturedProjectsSection, HTMLStencilElement {
    }
    var HTMLFeaturedProjectsSectionElement: {
        prototype: HTMLFeaturedProjectsSectionElement;
        new (): HTMLFeaturedProjectsSectionElement;
    };
    interface HTMLHeroSectionElement extends Components.HeroSection, HTMLStencilElement {
    }
    var HTMLHeroSectionElement: {
        prototype: HTMLHeroSectionElement;
        new (): HTMLHeroSectionElement;
    };
    interface HTMLPortfolioPageElement extends Components.PortfolioPage, HTMLStencilElement {
    }
    var HTMLPortfolioPageElement: {
        prototype: HTMLPortfolioPageElement;
        new (): HTMLPortfolioPageElement;
    };
    interface HTMLSiteHeaderElement extends Components.SiteHeader, HTMLStencilElement {
    }
    var HTMLSiteHeaderElement: {
        prototype: HTMLSiteHeaderElement;
        new (): HTMLSiteHeaderElement;
    };
    interface HTMLWhatIDoSectionElement extends Components.WhatIDoSection, HTMLStencilElement {
    }
    var HTMLWhatIDoSectionElement: {
        prototype: HTMLWhatIDoSectionElement;
        new (): HTMLWhatIDoSectionElement;
    };
    interface HTMLElementTagNameMap {
        "about-section": HTMLAboutSectionElement;
        "contact-section": HTMLContactSectionElement;
        "experience-section": HTMLExperienceSectionElement;
        "featured-projects-section": HTMLFeaturedProjectsSectionElement;
        "hero-section": HTMLHeroSectionElement;
        "portfolio-page": HTMLPortfolioPageElement;
        "site-header": HTMLSiteHeaderElement;
        "what-i-do-section": HTMLWhatIDoSectionElement;
    }
}
declare namespace LocalJSX {
    interface AboutSection {
    }
    interface ContactSection {
    }
    interface ExperienceSection {
    }
    interface FeaturedProjectsSection {
    }
    interface HeroSection {
    }
    interface PortfolioPage {
    }
    interface SiteHeader {
    }
    interface WhatIDoSection {
    }
    interface IntrinsicElements {
        "about-section": AboutSection;
        "contact-section": ContactSection;
        "experience-section": ExperienceSection;
        "featured-projects-section": FeaturedProjectsSection;
        "hero-section": HeroSection;
        "portfolio-page": PortfolioPage;
        "site-header": SiteHeader;
        "what-i-do-section": WhatIDoSection;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "about-section": LocalJSX.IntrinsicElements["about-section"] & JSXBase.HTMLAttributes<HTMLAboutSectionElement>;
            "contact-section": LocalJSX.IntrinsicElements["contact-section"] & JSXBase.HTMLAttributes<HTMLContactSectionElement>;
            "experience-section": LocalJSX.IntrinsicElements["experience-section"] & JSXBase.HTMLAttributes<HTMLExperienceSectionElement>;
            "featured-projects-section": LocalJSX.IntrinsicElements["featured-projects-section"] & JSXBase.HTMLAttributes<HTMLFeaturedProjectsSectionElement>;
            "hero-section": LocalJSX.IntrinsicElements["hero-section"] & JSXBase.HTMLAttributes<HTMLHeroSectionElement>;
            "portfolio-page": LocalJSX.IntrinsicElements["portfolio-page"] & JSXBase.HTMLAttributes<HTMLPortfolioPageElement>;
            "site-header": LocalJSX.IntrinsicElements["site-header"] & JSXBase.HTMLAttributes<HTMLSiteHeaderElement>;
            "what-i-do-section": LocalJSX.IntrinsicElements["what-i-do-section"] & JSXBase.HTMLAttributes<HTMLWhatIDoSectionElement>;
        }
    }
}
